// Generated by scripts/seed-prototype-assets.mjs
// Provider contracts are the seam between mock UX and real connectors.

import type { ProjectRequest } from '@/types/domain-models';

export interface ProjectRequestRepository {
  list(): Promise<ProjectRequest[]>;
  getById(id: string): Promise<ProjectRequest | null>;
  save(input: Partial<ProjectRequest>): Promise<ProjectRequest>;
}

export interface AppDataProvider {
  projectRequests: ProjectRequestRepository;
}
