// Generated by scripts/seed-prototype-assets.mjs
import { useQuery } from '@tanstack/react-query';
import { createAppDataProvider } from '@/services/providerFactory';

const provider = createAppDataProvider();

export const prototypeQueryKeys = {
  projectRequests: ['projectRequests'] as const,
  projectRequestById: (id: string) => ['projectRequests', id] as const,
};

export function useProjectRequests() {
  return useQuery({
    queryKey: prototypeQueryKeys.projectRequests,
    queryFn: () => provider.projectRequests.list(),
  });
}

export function useProjectRequest(id: string | undefined) {
  return useQuery({
    queryKey: prototypeQueryKeys.projectRequestById(id || 'new'),
    queryFn: () => (id ? provider.projectRequests.getById(id) : Promise.resolve(null)),
    enabled: Boolean(id),
  });
}
